name: Create docs

on:
  workflow_dispatch:
  push:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: windows-2019
    steps:

      # Clone Geode repo
      - name: Checkout Geode repo
        uses: actions/checkout@v3
        with:
          repository: 'geode-sdk/geode'
          path: 'geode'

      - name: Checkout docs repo
        uses: actions/checkout@v3
        with:
          path: 'geode/docs'
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libc6 libclang-cpp12 libclang1-12 libgcc-s1 libllvm12 libstdc++6 libxapian30
      
      - name: Download Flash
        uses: robinraju/release-downloader@v1.5
        with:
          repository: hjfod/flash
          latest: true
          fileName: "flash.exe"
          tarBall: false
          zipBall: false
          out-file-path: "flash" 
        
      - name: Add Flash to Path
        run: |
          echo "${{ github.workspace }}/flash" >> $GITHUB_PATH

      - name: Build docs with Flash
        run: |
          cd dist
          flash -i ../geode -o .

      - name: Setup Pages
        uses: actions/configure-pages@v2
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './dist'
        
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
